[libraries]
common.files = [
    'src/lib/**/*.vhd',
    'src/lib/*.vhd',
]
default.files = [
    'src/design/**/*.vhd',
    'src/design/*.vhd',
]
tb.files = [
    'src/testbench/**/*.vhd',
    'src/testbench/*.vhd',
]

[lint]
unused = 'error' # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement