[libraries]
common_lib.files = [
    'src/**/*.vhd',
    'src/*.vhd',
]

[lint]
unused = 'error' # Upgrade the 'unused' diagnostic to the 'error' severity
unnecessary_work_library = false # Disable linting for the 'library work;' statement